import type { AfterSalesData } from './after-sales-types'

export const FALLBACK_AFTER_SALES_DATA: AfterSalesData = {
  sourcesSyncedAt: new Date().toISOString(),
  warranties: [
    {
      id: 'warranty-car-flagship',
      vehicleType: 'car',
      modelSeries: 'VF 8 / VF 9 / Lux / President',
      models: ['VF 8', 'VF 9', 'VF 8 The All New', 'Lux A 2.0', 'Lux SA 2.0', 'President', 'Lạc Hồng 900LX'],
      warrantyTerm: '10 năm hoặc 200.000 km',
      batteryWarrantyTerm: '10 năm, không giới hạn số km (dung lượng tối thiểu 70%)',
      commercialWarranty: '5 năm hoặc 200.000 km',
      highlight: 'Thời hạn bảo hành vượt trội hàng đầu thị trường',
      conditions: [
        'Bảo hành bao gồm sửa chữa hoặc thay thế miễn phí phụ tùng chính hãng bị hư hỏng do lỗi vật liệu hoặc chế tạo.',
        'Bảo hành pin áp dụng thay thế hoặc sửa chữa nếu dung lượng khả dụng (SOH) giảm dưới 70% trong thời hạn bảo hành.',
        'Áp dụng tại toàn bộ hệ thống Xưởng dịch vụ FASTLANE & VinFast ủy quyền trên toàn quốc.',
      ],
    },
    {
      id: 'warranty-car-mainstream',
      vehicleType: 'car',
      modelSeries: 'VF 3 / VF 5 / VF 6 / VF 7 / VF e34 / VF MPV',
      models: ['VF 3', 'VF 5', 'VF 6', 'VF 7', 'VF e34', 'VF MPV 7', 'VF Minio Green', 'VF Nerio Green', 'VF Herio Green', 'VF Limo Green'],
      warrantyTerm: '7 năm hoặc 160.000 km',
      batteryWarrantyTerm: '8 năm hoặc 160.000 km (dung lượng tối thiểu 70%)',
      commercialWarranty: '3 năm hoặc 160.000 km',
      highlight: 'Chính sách bảo hành toàn diện cho xe điện thế hệ mới',
      conditions: [
        'Bảo hành chính hãng đối với hệ thống động cơ điện tử, bộ điều khiển và các linh kiện cơ khí chính.',
        'Miễn phí kiểm tra, cập nhật phần mềm điều khiển xe định kỳ (FOTA & tại xưởng).',
        'Bảo dưỡng và bảo hành đúng theo sổ hướng dẫn sử dụng xe.',
      ],
    },
    {
      id: 'warranty-car-van',
      vehicleType: 'car',
      modelSeries: 'VF EC Van',
      models: ['VF EC Van'],
      warrantyTerm: '5 năm hoặc 130.000 km',
      batteryWarrantyTerm: '5 năm hoặc 130.000 km',
      conditions: [
        'Bảo hành tối ưu hóa cho mục đích vận tải thương mại và chuyên dụng.',
        'Ưu tiên tiếp nhận nhanh tại các trạm dịch vụ lưu động và xưởng chuyên biệt.',
      ],
    },
    {
      id: 'warranty-motorbike-all',
      vehicleType: 'motorbike',
      modelSeries: 'Xe máy điện VinFast (Evo / Feliz / Klara / Vento / Theon)',
      models: ['Evo 200', 'Evo 200 Lite', 'Feliz S', 'Klara S (2022)', 'Vento S', 'Theon S', 'Ludo', 'Impes'],
      warrantyTerm: '3 năm không giới hạn số km',
      batteryWarrantyTerm: '3 năm không giới hạn km đối với Pin LFP',
      highlight: 'Pin LFP độ bền cao, bảo hành dài hạn',
      conditions: [
        'Bảo hành động cơ điện In-hub / Mid-motor, khung gầm và hệ thống điều khiển điện tử ECU.',
        'Pin LFP được bảo hành sửa chữa, phục hồi hoặc thay mới nếu dung lượng tụt giảm bất thường do lỗi kỹ thuật.',
        'Hỗ trợ đổi pin nhanh tại hệ thống xưởng dịch vụ và điểm ủy quyền.',
      ],
    },
    {
      id: 'warranty-bus-all',
      vehicleType: 'bus',
      modelSeries: 'Xe buýt điện VinBus',
      models: ['VinBus 12m', 'VinBus 10m'],
      warrantyTerm: '5 năm hoặc 300.000 km',
      batteryWarrantyTerm: '5 năm hoặc 300.000 km',
      conditions: [
        'Đội ngũ kỹ thuật viên chuyên trách 24/7 trực tiếp tại depot.',
        'Cung cấp phụ tùng dự phòng nhanh chóng cam kết thời gian hoàn thành sửa chữa.',
      ],
    },
  ],
  maintenances: [
    {
      id: 'maintenance-car',
      vehicleType: 'car',
      title: 'Bảo dưỡng định kỳ Ô tô điện',
      description: 'Quy trình bảo dưỡng xe điện tinh gọn, tiết kiệm tới 50% chi phí so với xe xăng truyền thống nhờ ít chi tiết chuyển động cơ học.',
      mobileServiceAvailable: true,
      intervals: [
        {
          mileageKm: 12000,
          months: 12,
          level: 'Cấp 1 (12.000 km)',
          description: 'Kiểm tra tổng quát hệ thống pin, chẩn đoán lỗi phần mềm, hệ thống phanh và kiểm tra lốp.',
          estimatedDuration: '45 - 60 phút',
          keyItems: [
            'Đọc lỗi và chẩn đoán toàn diện hệ thống điện cao áp (BMS)',
            'Kiểm tra độ mòn và áp suất lốp xe',
            'Kiểm tra hệ thống phanh tái sinh và phanh cơ học',
            'Kiểm tra hệ thống đèn chiếu sáng và gạt mưa',
            'Vệ sinh lọc gió điều hòa',
          ],
        },
        {
          mileageKm: 24000,
          months: 24,
          level: 'Cấp 2 (24.000 km)',
          description: 'Bảo dưỡng hệ thống điều hòa, thay lọc gió cabin, kiểm tra dung dịch làm mát pin và phanh.',
          estimatedDuration: '60 - 90 phút',
          keyItems: [
            'Tất cả hạng mục Cấp 1',
            'Thay thế lọc gió điều hòa không khí',
            'Kiểm tra và bổ sung nước làm mát khối pin chuyên dụng',
            'Kiểm tra độ rơ rotuyn và hệ thống treo gầm',
            'Bảo dưỡng và vệ sinh cụm phanh 4 bánh',
          ],
        },
        {
          mileageKm: 48000,
          months: 48,
          level: 'Cấp 3 (48.000 km)',
          description: 'Bảo dưỡng chuyên sâu hệ truyền động điện tử, thay dầu hộp giảm tốc và dầu phanh.',
          estimatedDuration: '90 - 120 phút',
          keyItems: [
            'Tất cả hạng mục Cấp 2',
            'Thay dầu hộp số giảm tốc truyền động động cơ điện',
            'Thay thế toàn bộ dầu phanh thủy lực (DOT 4)',
            'Kiểm tra độ siết các bu lông khung gầm và giá đỡ khối pin',
            'Cân bằng động và đảo lốp 4 bánh',
          ],
        },
      ],
      checklist: [
        {
          category: 'Hệ thống điện cao áp & Pin',
          items: ['Kiểm tra điện áp từng cell pin', 'Đo đạc độ cách điện', 'Kiểm tra cổng sạc AC/DC', 'Cập nhật firmware BMS'],
        },
        {
          category: 'Hệ thống truyền động & Khung gầm',
          items: ['Động cơ điện E-Motor', 'Hộp giảm tốc', 'Thước lái & Rotuyn', 'Hệ thống treo trước/sau'],
        },
        {
          category: 'Hệ thống an toàn & Điều khiển',
          items: ['Hệ thống phanh ABS/EBD/ESC', 'Cảm biến ADAS & Camera', 'Túi khí & dây an toàn', 'Áp suất lốp TPMS'],
        },
      ],
    },
    {
      id: 'maintenance-motorbike',
      vehicleType: 'motorbike',
      title: 'Bảo dưỡng định kỳ Xe máy điện',
      description: 'Quy trình kiểm tra nhanh chóng, bảo đảm an toàn hệ thống phanh, điện áp và lốp xe cho trải nghiệm lái êm ái mỗi ngày.',
      mobileServiceAvailable: true,
      intervals: [
        {
          mileageKm: 1000,
          months: 1,
          level: 'Bảo dưỡng đầu tiên (1.000 km)',
          description: 'Kiểm tra ban đầu, siết ốc toàn bộ khung sườn và kiểm tra phanh.',
          estimatedDuration: '20 - 30 phút',
          keyItems: ['Kiểm tra siết ốc khung xe', 'Đo dòng sạc pin', 'Căn chỉnh phanh trước/sau'],
        },
        {
          mileageKm: 5000,
          months: 6,
          level: 'Định kỳ 5.000 km hoặc 6 tháng',
          description: 'Kiểm tra hệ thống điện tử, vệ sinh cụm phanh, kiểm tra dầu phanh và lốp.',
          estimatedDuration: '30 - 45 phút',
          keyItems: ['Vệ sinh phanh', 'Kiểm tra độ mòn lốp', 'Tra mỡ trục cổ phốt và trục bánh', 'Kiểm tra giắc cắm động cơ'],
        },
        {
          mileageKm: 10000,
          months: 12,
          level: 'Định kỳ 10.000 km hoặc 12 tháng',
          description: 'Bảo dưỡng toàn diện hệ thống giảm xóc, thay thế dầu phanh và kiểm tra dung lượng pin.',
          estimatedDuration: '45 - 60 phút',
          keyItems: ['Thay dầu phanh', 'Kiểm tra giảm xóc', 'Cân chỉnh cổ phốt', 'Đo đạc dung lượng pin thực tế'],
        },
      ],
      checklist: [
        {
          category: 'Bộ pin & Động cơ',
          items: ['Khối pin LFP/Lithium', 'Động cơ điện Inhub/Mid-motor', 'Bộ điều khiển ECU', 'Cổng sạc và dây nguồn'],
        },
        {
          category: 'Cơ khí & An toàn',
          items: ['Phanh đĩa & má phanh', 'Lốp không săm', 'Hệ thống đèn LED chiếu sáng', 'Cổ phốt và giảm xóc'],
        },
      ],
    },
  ],
  repairs: [
    {
      id: 'repair-genuine-parts',
      title: 'Phụ tùng chính hãng 100%',
      badge: 'Cam kết chất lượng',
      description: 'Toàn bộ linh kiện và phụ tùng thay thế đều đạt tiêu chuẩn kỹ thuật nghiêm ngặt của nhà sản xuất, bảo hành chính hãng từ 12 đến 24 tháng.',
      features: [
        'Phụ tùng đóng gói niêm phong chính thức',
        'Bảo hành phụ tùng độc lập từ 1 - 2 năm',
        'Mức giá minh bạch niêm yết toàn quốc',
        'Sẵn sàng phụ tùng nhanh chóng với kho trung tâm hiện đại',
      ],
    },
    {
      id: 'repair-body-paint',
      title: 'Đồng sơn & Thân vỏ công nghệ cao',
      badge: 'Tiêu chuẩn quốc tế',
      description: 'Phòng sơn sấy hồng ngoại hiện đại, sử dụng sơn gốc nước cao cấp thân thiện môi trường, tái tạo độ bóng và màu sắc chuẩn gốc 100%.',
      features: [
        'Pha màu sơn vi tính quang phổ chuẩn xác',
        'Phòng sấy khép kín lọc bụi chuẩn phòng sạch',
        'Kéo nắn khung xe điện bằng thước đo 3D điện tử',
        'Bảo hành nước sơn lên tới 3 năm',
      ],
    },
    {
      id: 'repair-ev-diagnostics',
      title: 'Chẩn đoán điện cao áp & Phần mềm',
      badge: 'Kỹ thuật viên chứng chỉ EV',
      description: 'Đội ngũ chuyên gia được đào tạo bài bản về an toàn điện cao áp, trang bị máy chẩn đoán chuyên sâu đọc phân tích dữ liệu hộp đen và ECU.',
      features: [
        'Thiết bị đo cách điện và an toàn điện chuyên dụng',
        'Nâng cấp và hiệu chỉnh phần mềm quản lý pin (BMS)',
        'Sửa chữa module pin theo công nghệ độc quyền',
        'Khắc phục sự cố hệ thống tự hành ADAS & Cảm biến',
      ],
    },
    {
      id: 'repair-mobile-service',
      title: 'Dịch vụ sửa chữa lưu động (Mobile Service)',
      badge: 'Tiện lợi tận nơi',
      description: 'Xe dịch vụ lưu động được trang bị đầy đủ dụng cụ kỹ thuật và phụ tùng, phục vụ bảo dưỡng và sửa chữa nhanh ngay tại nhà hoặc cơ quan.',
      features: [
        'Đặt lịch linh hoạt theo khung giờ của khách hàng',
        'Kỹ thuật viên chuyên nghiệp đến tận địa chỉ yêu cầu',
        'Hỗ trợ bảo dưỡng định kỳ và thay thế phụ tùng hao mòn',
        'Không phụ thu chi phí di chuyển trong bán kính tiêu chuẩn',
      ],
    },
  ],
  rescues: [
    {
      id: 'rescue-policy-247',
      vehicleType: 'all',
      title: 'Cứu hộ khẩn cấp 24/7 toàn quốc',
      description: 'Dịch vụ cứu hộ hỗ trợ khách hàng không gián đoạn 24 giờ mỗi ngày, 7 ngày trong tuần, kể cả ngày lễ tết.',
      hotline: '1900 23 23 89',
      operatingHours: '24/7 Toàn quốc',
      mobileChargingSupport: true,
      coverage: [
        'Cứu hộ sạc pin lưu động khi xe hết điện giữa đường',
        'Cứu hộ lốp: vá lốp, thay lốp dự phòng, bơm lốp lưu động',
        'Kéo xe về xưởng dịch vụ gần nhất khi gặp sự cố kỹ thuật hoặc va chạm',
        'Xử lý kẹt khóa, kích bình ắc quy phụ 12V',
      ],
      conditions: [
        'Miễn phí cứu hộ kéo xe trong thời gian xe còn hạn bảo hành đối với các lỗi kỹ thuật phát sinh từ xe.',
        'Hỗ trợ sạc khẩn cấp với chi phí hợp lý để xe di chuyển được tới trạm sạc gần nhất.',
        'Khách hàng chỉ cần gọi hotline và cung cấp vị trí, biển số xe và tình trạng sự cố.',
      ],
    },
  ],
  workshops: [
    {
      id: 'ws-hn-01',
      name: 'Xưởng Dịch Vụ FASTLANE - Vincom Ocean Park',
      city: 'Hà Nội',
      district: 'Gia Lâm',
      address: 'Tầng hầm B1, TTTM Vincom Mega Mall Ocean Park, Gia Lâm, Hà Nội',
      phone: '024 3975 0001',
      operatingHours: '08:00 - 18:00 (Thứ 2 - Chủ Nhật)',
      services: ['car', 'charging', 'quick_service', 'body_paint'],
    },
    {
      id: 'ws-hn-02',
      name: 'Xưởng Dịch Vụ FASTLANE - Phạm Hùng',
      city: 'Hà Nội',
      district: 'Nam Từ Liêm',
      address: 'Số 1 Phạm Hùng, Phường Mỹ Đình 2, Quận Nam Từ Liêm, Hà Nội',
      phone: '024 3975 0002',
      operatingHours: '08:00 - 18:00 (Thứ 2 - Thứ 7)',
      services: ['car', 'motorbike', 'charging', 'body_paint', 'quick_service'],
    },
    {
      id: 'ws-hcm-01',
      name: 'Xưởng Dịch Vụ FASTLANE - Landmark 81',
      city: 'TP. Hồ Chí Minh',
      district: 'Bình Thạnh',
      address: 'Tầng B2, Tòa nhà Landmark 81, 720A Điện Biên Phủ, Phường 22, Quận Bình Thạnh, TP. HCM',
      phone: '028 3975 0001',
      operatingHours: '08:00 - 18:00 (Thứ 2 - Chủ Nhật)',
      services: ['car', 'charging', 'quick_service'],
    },
    {
      id: 'ws-hcm-02',
      name: 'Xưởng Dịch Vụ FASTLANE - Thảo Điền',
      city: 'TP. Hồ Chí Minh',
      district: 'TP. Thủ Đức',
      address: '159 Xa Lộ Hà Nội, Phường Thảo Điền, TP. Thủ Đức, TP. HCM',
      phone: '028 3975 0002',
      operatingHours: '08:00 - 18:00 (Thứ 2 - Thứ 7)',
      services: ['car', 'motorbike', 'charging', 'body_paint', 'quick_service'],
    },
    {
      id: 'ws-dn-01',
      name: 'Xưởng Dịch Vụ FASTLANE - Đà Nẵng',
      city: 'Đà Nẵng',
      district: 'Hải Châu',
      address: '910A Ngô Quyền, Phường An Hải Bắc, Quận Sơn Trà, TP. Đà Nẵng',
      phone: '0236 3975 001',
      operatingHours: '08:00 - 18:00 (Thứ 2 - Thứ 7)',
      services: ['car', 'motorbike', 'charging', 'body_paint', 'quick_service'],
    },
    {
      id: 'ws-hp-01',
      name: 'Xưởng Dịch Vụ FASTLANE - Hải Phòng',
      city: 'Hải Phòng',
      district: 'Lê Chân',
      address: 'Số 1 Lê Thánh Tông, Phường Máy Tơ, Quận Ngô Quyền, TP. Hải Phòng',
      phone: '0225 3975 001',
      operatingHours: '08:00 - 18:00 (Thứ 2 - Thứ 7)',
      services: ['car', 'motorbike', 'charging', 'body_paint', 'quick_service'],
    },
    {
      id: 'ws-ct-01',
      name: 'Xưởng Dịch Vụ FASTLANE - Cần Thơ',
      city: 'Cần Thơ',
      district: 'Ninh Kiều',
      address: '209 Đường 30/4, Phường Xuân Khánh, Quận Ninh Kiều, TP. Cần Thơ',
      phone: '0292 3975 001',
      operatingHours: '08:00 - 18:00 (Thứ 2 - Thứ 7)',
      services: ['car', 'motorbike', 'charging', 'quick_service'],
    },
  ],
}
