import type { SpecAlias, SpecDefinition } from './types'

export const CORE_SPEC_DEFINITIONS: readonly SpecDefinition[] = [
  { canonicalKey: 'range_km', labelVi: 'Quãng đường di chuyển', labelEn: 'Range', valueType: 'NUMBER', unitDimension: 'DISTANCE', canonicalUnit: 'km', sortable: true, searchable: true, rankingAggregation: 'MAX' },
  { canonicalKey: 'top_speed_kmh', labelVi: 'Tốc độ tối đa', labelEn: 'Top speed', valueType: 'NUMBER', unitDimension: 'SPEED', canonicalUnit: 'km/h', sortable: true, searchable: true, rankingAggregation: 'MAX' },
  { canonicalKey: 'max_power_kw', labelVi: 'Công suất tối đa', labelEn: 'Maximum power', valueType: 'NUMBER', unitDimension: 'POWER', canonicalUnit: 'kW', sortable: true, searchable: true, rankingAggregation: 'MAX' },
  { canonicalKey: 'max_torque_nm', labelVi: 'Mô-men xoắn cực đại', labelEn: 'Maximum torque', valueType: 'NUMBER', unitDimension: 'TORQUE', canonicalUnit: 'Nm', sortable: true, searchable: true, rankingAggregation: 'MAX' },
  { canonicalKey: 'battery_capacity_kwh', labelVi: 'Dung lượng pin', labelEn: 'Battery capacity', valueType: 'NUMBER', unitDimension: 'ENERGY', canonicalUnit: 'kWh', sortable: true, searchable: true, rankingAggregation: 'MAX' },
  { canonicalKey: 'charging_time', labelVi: 'Thời gian sạc', labelEn: 'Charging time', valueType: 'DURATION', unitDimension: 'TIME', canonicalUnit: 'second', sortable: false, searchable: true },
  { canonicalKey: 'dimensions_mm', labelVi: 'Kích thước (D x R x C)', labelEn: 'Dimensions', valueType: 'TEXT', canonicalUnit: 'mm', sortable: false, searchable: true },
  { canonicalKey: 'seats', labelVi: 'Số chỗ ngồi', labelEn: 'Seats', valueType: 'NUMBER', unitDimension: 'COUNT', canonicalUnit: 'seat', sortable: true, searchable: true, rankingAggregation: 'MAX' },
  { canonicalKey: 'drive_type', labelVi: 'Hệ dẫn động', labelEn: 'Drive type', valueType: 'TEXT', sortable: false, searchable: true },
] as const
const alias = (
  definitionKey: string,
  value: string,
  productType: SpecAlias['productType'] = '*',
  matchKind: SpecAlias['matchKind'] = 'LABEL',
  sourceSchema: string = '*',
): SpecAlias => ({ definitionKey, alias: value, productType, sourceSchema, matchKind })

export const CORE_SPEC_ALIASES: readonly SpecAlias[] = [
  alias('range_km', 'specs.*.specs.powertrain.distance', 'CAR', 'PATH'),
  alias('max_power_kw', 'specs.*.specs.powertrain.maxPower', 'CAR', 'PATH'),
  alias('max_torque_nm', 'specs.*.specs.powertrain.maxTorque', 'CAR', 'PATH'),
  alias('top_speed_kmh', 'specs.*.specs.powertrain.topSpeed', 'CAR', 'PATH'),
  alias('drive_type', 'specs.*.specs.powertrain.drivetrain', 'CAR', 'PATH'),
  alias('battery_capacity_kwh', 'specs.*.specs.powertrain.batteryCapacity', 'CAR', 'PATH'),
  alias('charging_time', 'specs.*.specs.powertrain.fastChargingTime', 'CAR', 'PATH'),
  alias('dimensions_mm', 'specs.*.specs.dimension.length', 'CAR', 'PATH'),
  alias('seats', 'specs.*.specs.interior.numberOfSeats', 'CAR', 'PATH'),

  alias('range_km', 'Quãng đường đi được mỗi lần sạc', 'MOTORBIKE'),
  alias('range_km', 'Quãng đường đi được', 'MOTORBIKE'),
  alias('range_km', 'Quãng đường 1 lần sạc (2 pin)', 'MOTORBIKE'),
  alias('range_km', 'Quãng đường', 'MOTORBIKE'),
  alias('range_km', 'Phạm vi hoạt động', 'MOTORBIKE'),
  alias('max_power_kw', 'Công suất tối đa', 'MOTORBIKE'),
  alias('max_power_kw', 'Công suất lớn nhất', 'MOTORBIKE'),
  alias('max_power_kw', 'Công suất', 'MOTORBIKE'),
  alias('max_torque_nm', 'Mô-men xoắn cực đại', 'MOTORBIKE'),
  alias('max_torque_nm', 'Momen xoắn cực đại', 'MOTORBIKE'),
  alias('top_speed_kmh', 'Tốc độ tối đa', 'MOTORBIKE'),
  alias('top_speed_kmh', 'Tốc độ tối đa - SPORT', 'MOTORBIKE'),
  alias('top_speed_kmh', 'Vận tốc', 'MOTORBIKE'),
  alias('top_speed_kmh', 'Vận tốc lên tới', 'MOTORBIKE'),
  alias('drive_type', 'Loại động cơ', 'MOTORBIKE'),
  alias('battery_capacity_kwh', 'Dung lượng pin/ắc quy', 'MOTORBIKE'),
  alias('battery_capacity_kwh', 'Dung lượng pin', 'MOTORBIKE'),
  alias('battery_capacity_kwh', 'Dung lượng ắc quy', 'MOTORBIKE'),
  alias('charging_time', 'Thời gian sạc tiêu chuẩn', 'MOTORBIKE'),
  alias('charging_time', 'Thời gian sạc nhanh', 'MOTORBIKE'),
  alias('dimensions_mm', 'Dài x Rộng x Cao (mm)', 'MOTORBIKE'),
  alias('dimensions_mm', 'Dài x Rộng x Cao', 'MOTORBIKE'),
  alias('dimensions_mm', 'Kích thước (D x R x C)', 'MOTORBIKE'),
  alias('seats', 'Số chỗ ngồi', 'MOTORBIKE'),
  alias('seats', 'Số người chở', 'MOTORBIKE'),

  // Flat car fields are retained as a deterministic compatibility source.
  alias('range_km', 'Quãng đường đi được', 'CAR'),
  alias('max_power_kw', 'Công suất tối đa', 'CAR'),
  alias('max_torque_nm', 'Mô-men xoắn cực đại', 'CAR'),
  alias('top_speed_kmh', 'Tốc độ tối đa', 'CAR'),
  alias('drive_type', 'Hệ dẫn động', 'CAR'),
  alias('battery_capacity_kwh', 'Dung lượng pin', 'CAR'),
  alias('charging_time', 'Thời gian sạc nhanh', 'CAR'),
  alias('dimensions_mm', 'Dài x Rộng x Cao', 'CAR'),
  alias('seats', 'Số chỗ ngồi', 'CAR'),
] as const
