import type { SpecAlias, SpecDefinition } from './types'

export const CORE_SPEC_DEFINITIONS: readonly SpecDefinition[] = [
  { canonicalKey: 'range_km', labelVi: 'Quãng đường di chuyển', labelEn: 'Range', valueType: 'NUMBER', unitDimension: 'DISTANCE', canonicalUnit: 'km', sortable: true, searchable: true, rankingAggregation: 'MAX' },
  { canonicalKey: 'top_speed_kmh', labelVi: 'Tốc độ tối đa', labelEn: 'Top speed', valueType: 'NUMBER', unitDimension: 'SPEED', canonicalUnit: 'km/h', sortable: true, searchable: true, rankingAggregation: 'MAX' },
  { canonicalKey: 'max_power_kw', labelVi: 'Công suất tối đa', labelEn: 'Maximum power', valueType: 'NUMBER', unitDimension: 'POWER', canonicalUnit: 'kW', sortable: true, searchable: true, rankingAggregation: 'MAX' },
  { canonicalKey: 'max_torque_nm', labelVi: 'Mô-men xoắn cực đại', labelEn: 'Maximum torque', valueType: 'NUMBER', unitDimension: 'TORQUE', canonicalUnit: 'Nm', sortable: true, searchable: true, rankingAggregation: 'MAX' },
  { canonicalKey: 'battery_capacity_kwh', labelVi: 'Dung lượng pin', labelEn: 'Battery capacity', valueType: 'NUMBER', unitDimension: 'ENERGY', canonicalUnit: 'kWh', sortable: true, searchable: true, rankingAggregation: 'MAX' },
  { canonicalKey: 'charging_time', labelVi: 'Thời gian sạc', labelEn: 'Charging time', valueType: 'DURATION', unitDimension: 'TIME', canonicalUnit: 'second', sortable: false, searchable: true },
  { canonicalKey: 'dimensions_mm', labelVi: 'Kích thước (D x R x C)', labelEn: 'Dimensions', valueType: 'TEXT', canonicalUnit: 'mm', sortable: false, searchable: true },
  { canonicalKey: 'seats', labelVi: 'Số chỗ ngồi', labelEn: 'Seats', valueType: 'NUMBER', unitDimension: 'COUNT', canonicalUnit: 'seat', sortable: true, searchable: true, rankingAggregation: 'MAX' },
  { canonicalKey: 'drive_type', labelVi: 'Hệ dẫn động', labelEn: 'Drive type', valueType: 'TEXT', sortable: false, searchable: true },
] as const

export const REVIEWED_SPEC_DEFINITIONS: readonly SpecDefinition[] = [
  { canonicalKey: 'rated_power_kw', labelVi: 'Công suất danh định', labelEn: 'Rated power', valueType: 'NUMBER', unitDimension: 'POWER', canonicalUnit: 'kW', sortable: true, searchable: true, rankingAggregation: 'MAX' },
  { canonicalKey: 'wheelbase_mm', labelVi: 'Chiều dài cơ sở', labelEn: 'Wheelbase', valueType: 'NUMBER', unitDimension: 'LENGTH', canonicalUnit: 'mm', sortable: true, searchable: true, rankingAggregation: 'MAX' },
  { canonicalKey: 'ground_clearance_mm', labelVi: 'Khoảng sáng gầm', labelEn: 'Ground clearance', valueType: 'NUMBER', unitDimension: 'LENGTH', canonicalUnit: 'mm', sortable: true, searchable: true, rankingAggregation: 'MAX' },
  { canonicalKey: 'seat_height_mm', labelVi: 'Chiều cao yên', labelEn: 'Seat height', valueType: 'NUMBER', unitDimension: 'LENGTH', canonicalUnit: 'mm', sortable: true, searchable: true, rankingAggregation: 'MIN' },
  { canonicalKey: 'tire_spec', labelVi: 'Kích thước lốp trước/sau', labelEn: 'Tire specification', valueType: 'TEXT', sortable: false, searchable: true },
  { canonicalKey: 'suspension_system', labelVi: 'Hệ thống giảm xóc', labelEn: 'Suspension system', valueType: 'TEXT', sortable: false, searchable: true },
  { canonicalKey: 'lock_type', labelVi: 'Loại khóa', labelEn: 'Lock type', valueType: 'TEXT', sortable: false, searchable: true },
  { canonicalKey: 'battery_type', labelVi: 'Loại pin/ắc quy', labelEn: 'Battery type', valueType: 'TEXT', sortable: false, searchable: true },
  { canonicalKey: 'charger_type', labelVi: 'Loại sạc', labelEn: 'Charger type', valueType: 'TEXT', sortable: false, searchable: true },
  { canonicalKey: 'trunk_volume_l', labelVi: 'Thể tích cốp', labelEn: 'Trunk volume', valueType: 'NUMBER', unitDimension: 'VOLUME', canonicalUnit: 'L', sortable: true, searchable: true, rankingAggregation: 'MAX' },
  { canonicalKey: 'motor_ip_rating', labelVi: 'Tiêu chuẩn chống nước động cơ', labelEn: 'Motor ingress protection', valueType: 'TEXT', sortable: false, searchable: true },
  { canonicalKey: 'battery_weight_kg', labelVi: 'Trọng lượng pin/ắc quy', labelEn: 'Battery weight', valueType: 'NUMBER', unitDimension: 'MASS', canonicalUnit: 'kg', sortable: true, searchable: true, rankingAggregation: 'MIN' },
  { canonicalKey: 'battery_location', labelVi: 'Vị trí lắp pin', labelEn: 'Battery location', valueType: 'TEXT', sortable: false, searchable: true },
  { canonicalKey: 'acceleration_time', labelVi: 'Thời gian tăng tốc', labelEn: 'Acceleration time', valueType: 'DURATION', unitDimension: 'TIME', canonicalUnit: 'second', sortable: true, searchable: true, rankingAggregation: 'MIN' },
  { canonicalKey: 'climbing_speed_kmh', labelVi: 'Tốc độ leo dốc', labelEn: 'Climbing speed', valueType: 'NUMBER', unitDimension: 'SPEED', canonicalUnit: 'km/h', sortable: true, searchable: true, rankingAggregation: 'MAX' },
  { canonicalKey: 'brake_system', labelVi: 'Hệ thống phanh', labelEn: 'Brake system', valueType: 'TEXT', sortable: false, searchable: true },
  { canonicalKey: 'payload_kg', labelVi: 'Tải trọng', labelEn: 'Payload', valueType: 'NUMBER', unitDimension: 'MASS', canonicalUnit: 'kg', sortable: true, searchable: true, rankingAggregation: 'MAX' },
  { canonicalKey: 'vehicle_weight_kg', labelVi: 'Trọng lượng xe', labelEn: 'Vehicle weight', valueType: 'NUMBER', unitDimension: 'MASS', canonicalUnit: 'kg', sortable: true, searchable: true, rankingAggregation: 'MIN' },
  { canonicalKey: 'headlight_system', labelVi: 'Đèn chiếu sáng phía trước', labelEn: 'Headlight system', valueType: 'TEXT', sortable: false, searchable: true },
  { canonicalKey: 'infotainment_display', labelVi: 'Màn hình thông tin/giải trí', labelEn: 'Infotainment display', valueType: 'TEXT', sortable: false, searchable: true },
  { canonicalKey: 'dc_charging_power_kw', labelVi: 'Công suất sạc nhanh DC tối đa', labelEn: 'Maximum DC charging power', valueType: 'NUMBER', unitDimension: 'POWER', canonicalUnit: 'kW', sortable: true, searchable: true, rankingAggregation: 'MAX' },
  { canonicalKey: 'abs', labelVi: 'Chống bó cứng phanh ABS', labelEn: 'ABS', valueType: 'BOOLEAN', sortable: false, searchable: true },
  { canonicalKey: 'air_conditioner', labelVi: 'Điều hòa', labelEn: 'Air conditioner', valueType: 'TEXT', sortable: false, searchable: true },
  { canonicalKey: 'driver_seat_adjustment', labelVi: 'Điều chỉnh ghế lái', labelEn: 'Driver seat adjustment', valueType: 'TEXT', sortable: false, searchable: true },
  { canonicalKey: 'wheel_spec', labelVi: 'Thông số la-zăng', labelEn: 'Wheel specification', valueType: 'TEXT', sortable: false, searchable: true },
  { canonicalKey: 'ebd', labelVi: 'Phân phối lực phanh điện tử EBD', labelEn: 'EBD', valueType: 'BOOLEAN', sortable: false, searchable: true },
  { canonicalKey: 'airbag_count', labelVi: 'Số túi khí', labelEn: 'Airbag count', valueType: 'NUMBER', unitDimension: 'COUNT', canonicalUnit: 'airbag', sortable: true, searchable: true, rankingAggregation: 'MAX' },
  { canonicalKey: 'curb_weight_payload', labelVi: 'Khối lượng không tải / tải trọng', labelEn: 'Curb weight / payload', valueType: 'TEXT', canonicalUnit: 'kg', sortable: false, searchable: true },
  { canonicalKey: 'audio_system', labelVi: 'Hệ thống âm thanh', labelEn: 'Audio system', valueType: 'TEXT', sortable: false, searchable: true },
] as const

export const CATALOG_SPEC_DEFINITIONS: readonly SpecDefinition[] = [
  ...CORE_SPEC_DEFINITIONS,
  ...REVIEWED_SPEC_DEFINITIONS,
]

const alias = (
  definitionKey: string,
  value: string,
  productType: SpecAlias['productType'] = '*',
  matchKind: SpecAlias['matchKind'] = 'LABEL',
  sourceSchema: string = '*',
  options: Pick<SpecAlias, 'implicitUnit' | 'qualifiers'> = {},
): SpecAlias => ({ definitionKey, alias: value, productType, sourceSchema, matchKind, ...options })

export const CORE_SPEC_ALIASES: readonly SpecAlias[] = [
  alias('range_km', 'specs.*.specs.powertrain.distance', 'CAR', 'PATH', '*', { implicitUnit: 'km' }),
  alias('max_power_kw', 'specs.*.specs.powertrain.maxPower', 'CAR', 'PATH', 'fastlane_car_nested_v1', { implicitUnit: 'hp' }),
  alias('max_torque_nm', 'specs.*.specs.powertrain.maxTorque', 'CAR', 'PATH', '*', { implicitUnit: 'nm' }),
  alias('top_speed_kmh', 'specs.*.specs.powertrain.topSpeed', 'CAR', 'PATH', '*', { implicitUnit: 'km/h' }),
  alias('drive_type', 'specs.*.specs.powertrain.drivetrain', 'CAR', 'PATH'),
  alias('battery_capacity_kwh', 'specs.*.specs.powertrain.batteryCapacity', 'CAR', 'PATH', '*', { implicitUnit: 'kwh' }),
  alias('charging_time', 'specs.*.specs.powertrain.fastChargingTime', 'CAR', 'PATH'),
  alias('dimensions_mm', 'specs.*.specs.dimension.length', 'CAR', 'PATH'),
  alias('seats', 'specs.*.specs.interior.numberOfSeats', 'CAR', 'PATH', '*', { implicitUnit: 'count' }),

  alias('range_km', 'Quãng đường đi được mỗi lần sạc', 'MOTORBIKE', 'LABEL', '*', { implicitUnit: 'km' }),
  alias('range_km', 'Quãng đường đi được', 'MOTORBIKE', 'LABEL', '*', { implicitUnit: 'km' }),
  alias('range_km', 'Quãng đường 1 lần sạc (2 pin)', 'MOTORBIKE', 'LABEL', '*', { implicitUnit: 'km', qualifiers: [{ key: 'battery_count', value: 2, unit: 'battery' }] }),
  alias('range_km', 'Quãng đường', 'MOTORBIKE', 'LABEL', '*', { implicitUnit: 'km' }),
  alias('range_km', 'Phạm vi hoạt động', 'MOTORBIKE', 'LABEL', '*', { implicitUnit: 'km' }),
  alias('max_power_kw', 'Công suất tối đa', 'MOTORBIKE', 'LABEL', '*', { implicitUnit: 'w' }),
  alias('max_power_kw', 'Công suất lớn nhất', 'MOTORBIKE', 'LABEL', '*', { implicitUnit: 'w' }),
  alias('max_power_kw', 'Công suất', 'MOTORBIKE', 'LABEL', '*', { implicitUnit: 'w' }),
  alias('max_torque_nm', 'Mô-men xoắn cực đại', 'MOTORBIKE', 'LABEL', '*', { implicitUnit: 'nm' }),
  alias('max_torque_nm', 'Momen xoắn cực đại', 'MOTORBIKE', 'LABEL', '*', { implicitUnit: 'nm' }),
  alias('top_speed_kmh', 'Tốc độ tối đa', 'MOTORBIKE', 'LABEL', '*', { implicitUnit: 'km/h' }),
  alias('top_speed_kmh', 'Tốc độ tối đa - SPORT', 'MOTORBIKE', 'LABEL', '*', { implicitUnit: 'km/h', qualifiers: [{ key: 'drive_mode', value: 'SPORT' }] }),
  alias('top_speed_kmh', 'Vận tốc', 'MOTORBIKE', 'LABEL', '*', { implicitUnit: 'km/h' }),
  alias('top_speed_kmh', 'Vận tốc lên tới', 'MOTORBIKE', 'LABEL', '*', { implicitUnit: 'km/h' }),
  alias('drive_type', 'Loại động cơ', 'MOTORBIKE'),
  alias('battery_capacity_kwh', 'Dung lượng pin/ắc quy', 'MOTORBIKE', 'LABEL', '*', { implicitUnit: 'kwh' }),
  alias('battery_capacity_kwh', 'Dung lượng pin', 'MOTORBIKE', 'LABEL', '*', { implicitUnit: 'kwh' }),
  alias('battery_capacity_kwh', 'Dung lượng ắc quy', 'MOTORBIKE', 'LABEL', '*', { implicitUnit: 'kwh' }),
  alias('charging_time', 'Thời gian sạc tiêu chuẩn', 'MOTORBIKE', 'LABEL', '*', { qualifiers: [{ key: 'charging_mode', value: 'STANDARD' }] }),
  alias('charging_time', 'Thời gian sạc nhanh', 'MOTORBIKE'),
  alias('dimensions_mm', 'Dài x Rộng x Cao (mm)', 'MOTORBIKE'),
  alias('dimensions_mm', 'Dài x Rộng x Cao', 'MOTORBIKE'),
  alias('dimensions_mm', 'Kích thước (D x R x C)', 'MOTORBIKE'),
  alias('seats', 'Số chỗ ngồi', 'MOTORBIKE', 'LABEL', '*', { implicitUnit: 'count' }),
  alias('seats', 'Số người chở', 'MOTORBIKE', 'LABEL', '*', { implicitUnit: 'count' }),

  // Flat car fields are retained as a deterministic compatibility source.
  alias('range_km', 'Quãng đường đi được', 'CAR', 'LABEL', '*', { implicitUnit: 'km' }),
  alias('max_power_kw', 'Công suất tối đa', 'CAR', 'LABEL', '*', { implicitUnit: 'kw' }),
  alias('max_torque_nm', 'Mô-men xoắn cực đại', 'CAR', 'LABEL', '*', { implicitUnit: 'nm' }),
  alias('top_speed_kmh', 'Tốc độ tối đa', 'CAR', 'LABEL', '*', { implicitUnit: 'km/h' }),
  alias('drive_type', 'Hệ dẫn động', 'CAR'),
  alias('battery_capacity_kwh', 'Dung lượng pin', 'CAR', 'LABEL', '*', { implicitUnit: 'kwh' }),
  alias('charging_time', 'Thời gian sạc nhanh', 'CAR'),
  alias('dimensions_mm', 'Dài x Rộng x Cao', 'CAR'),
  alias('seats', 'Số chỗ ngồi', 'CAR', 'LABEL', '*', { implicitUnit: 'count' }),
] as const

export const REVIEWED_SPEC_ALIASES: readonly SpecAlias[] = [
  alias('rated_power_kw', 'Công suất danh định', 'MOTORBIKE'),
  alias('wheelbase_mm', 'Khoảng cách trục bánh Trước-Sau', 'MOTORBIKE'),
  alias('ground_clearance_mm', 'Khoảng sáng gầm', 'MOTORBIKE'),
  alias('seat_height_mm', 'Chiều cao yên', 'MOTORBIKE'),
  alias('tire_spec', 'Kích thước lốp Trước - Sau', 'MOTORBIKE'),
  alias('suspension_system', 'Giảm xóc trước và sau', 'MOTORBIKE'),
  alias('lock_type', 'Khóa xe', 'MOTORBIKE'),
  alias('battery_type', 'Loại pin/ắc quy', 'MOTORBIKE'),
  alias('charger_type', 'Loại sạc', 'MOTORBIKE'),
  alias('trunk_volume_l', 'Thể tích cốp', 'MOTORBIKE'),
  alias('motor_ip_rating', 'Tiêu chuẩn chống nước động cơ', 'MOTORBIKE'),
  alias('battery_weight_kg', 'Trọng lượng pin/ắc quy', 'MOTORBIKE', 'LABEL', '*', { implicitUnit: 'kg' }),
  alias('battery_location', 'Vị trí lắp pin', 'MOTORBIKE'),
  alias('acceleration_time', 'Gia tốc 0 - 50 km/h', 'MOTORBIKE', 'LABEL', '*', { qualifiers: [{ key: 'start_speed_kmh', value: 0, unit: 'km/h' }, { key: 'end_speed_kmh', value: 50, unit: 'km/h' }] }),
  alias('acceleration_time', 'Gia tốc 0 - 40 km/h', 'MOTORBIKE', 'LABEL', '*', { qualifiers: [{ key: 'start_speed_kmh', value: 0, unit: 'km/h' }, { key: 'end_speed_kmh', value: 40, unit: 'km/h' }] }),
  alias('climbing_speed_kmh', 'Khả năng leo dốc 20%', 'MOTORBIKE', 'LABEL', '*', { qualifiers: [{ key: 'grade_percent', value: 20, unit: '%' }] }),
  alias('brake_system', 'Phanh trước và sau', 'MOTORBIKE'),
  alias('payload_kg', 'Tải trọng', 'MOTORBIKE'),
  alias('vehicle_weight_kg', 'Trọng lượng xe', 'MOTORBIKE'),
  alias('headlight_system', 'Đèn pha trước', 'MOTORBIKE'),
  alias('top_speed_kmh', 'Tốc độ tối đa - ECO', 'MOTORBIKE', 'LABEL', '*', { qualifiers: [{ key: 'drive_mode', value: 'ECO' }] }),

  alias('wheelbase_mm', 'specs.*.specs.dimension.wheelbase', 'CAR', 'PATH', '*', { implicitUnit: 'mm' }),
  alias('ground_clearance_mm', 'specs.*.specs.dimension.croundClearance', 'CAR', 'PATH', '*', { implicitUnit: 'mm' }),
  alias('ground_clearance_mm', 'specs.*.specs.dimension.groundClearance', 'CAR', 'PATH', '*', { implicitUnit: 'mm' }),
  alias('curb_weight_payload', 'specs.*.specs.dimension.kurbWeightPayload', 'CAR', 'PATH'),
  alias('headlight_system', 'specs.*.specs.exterior.auto', 'CAR', 'PATH'),
  alias('wheel_spec', 'specs.*.specs.exterior.lazang', 'CAR', 'PATH'),
  alias('air_conditioner', 'specs.*.specs.interior.airConditioner', 'CAR', 'PATH'),
  alias('driver_seat_adjustment', 'specs.*.specs.interior.driverSeatAdjustment', 'CAR', 'PATH'),
  alias('infotainment_display', 'specs.*.specs.interior.informationCenter', 'CAR', 'PATH'),
  alias('infotainment_display', 'specs.*.specs.interior.infoCenter', 'CAR', 'PATH'),
  alias('audio_system', 'specs.*.specs.interior.audioSystem', 'CAR', 'PATH'),
  alias('dc_charging_power_kw', 'specs.*.specs.powertrain.maxDCCharging', 'CAR', 'PATH', '*', { implicitUnit: 'kw' }),
  alias('abs', 'specs.*.specs.safety.abs', 'CAR', 'PATH'),
  alias('ebd', 'specs.*.specs.safety.ebd', 'CAR', 'PATH'),
  alias('airbag_count', 'specs.*.specs.safety.airbagSystem', 'CAR', 'PATH', '*', { implicitUnit: 'count' }),
] as const

export const CATALOG_SPEC_ALIASES: readonly SpecAlias[] = [
  ...CORE_SPEC_ALIASES,
  ...REVIEWED_SPEC_ALIASES,
]
