begin;

-- New accessory variants receive an inventory-owned, database-generated SKU.
-- Existing SKU values are never rewritten; the sequence is only advanced past
-- the largest legacy ACS number before it is first used.
create sequence if not exists public.accessory_sku_sequence
  as bigint
  minvalue 1
  maxvalue 99999999
  start with 30000001
  increment by 1
  no cycle;

select setval(
  'public.accessory_sku_sequence'::regclass,
  greatest(
    30000000,
    coalesce((
      select max(substring(variant.sku from '^ACS([0-9]{8})$')::bigint)
        from public.product_variants variant
       where variant.sku ~ '^ACS[0-9]{8}$'
    ), 0),
    (select case when is_called then last_value else last_value - 1 end
       from public.accessory_sku_sequence)
  ),
  true
);

revoke all on sequence public.accessory_sku_sequence from public, anon, authenticated, service_role;
grant usage, select on sequence public.accessory_sku_sequence to service_role;

create or replace function public.save_admin_accessory_product_v3(
  target_product_id uuid,
  expected_updated_at timestamptz,
  target_payload jsonb
)
returns jsonb
language plpgsql
set search_path = pg_catalog, public
as $function$
declare
  v_variant jsonb;
  v_variant_index integer := 0;
  v_image_urls jsonb;
  v_invalid_count integer;
  v_variant_id uuid;
  v_existing_sku text;
  v_generated_sku text;
  v_variants jsonb := '[]'::jsonb;
  v_payload jsonb;
  v_source_variants jsonb;
  v_representative jsonb;
  v_sequence_value bigint;
begin
  if jsonb_typeof(target_payload) <> 'object'
     or jsonb_typeof(target_payload -> 'variants') <> 'array'
     or jsonb_array_length(target_payload -> 'variants') < 1 then
    raise exception using errcode = '22023', message = 'Accessory SKU payload is incomplete.';
  end if;

  for v_variant in
    select item.value
      from jsonb_array_elements(target_payload -> 'variants') item(value)
  loop
    if jsonb_typeof(v_variant) is distinct from 'object' then
      raise exception using errcode = '22023', message = format('variants.%s must be an object.', v_variant_index);
    end if;
    if v_variant ? 'sku' then
      raise exception using errcode = '22023', message = format('variants.%s.sku is generated by the database.', v_variant_index);
    end if;

    v_image_urls := v_variant -> 'imageUrls';
    if jsonb_typeof(v_image_urls) is distinct from 'array'
       or jsonb_array_length(v_image_urls) < 1
       or jsonb_array_length(v_image_urls) > 20 then
      raise exception using errcode = '23514', message = format('variants.%s.imageUrls must contain 1 to 20 direct URLs.', v_variant_index);
    end if;
    select count(*) into v_invalid_count
      from jsonb_array_elements_text(v_image_urls) url(value)
     where url.value !~* '^https?://[^[:space:]]+$';
    if v_invalid_count > 0 then
      raise exception using errcode = '23514', message = format('variants.%s.imageUrls must contain HTTP or HTTPS URLs.', v_variant_index);
    end if;
    select count(*) - count(distinct url.value) into v_invalid_count
      from jsonb_array_elements_text(v_image_urls) url(value);
    if v_invalid_count > 0 then
      raise exception using errcode = '23514', message = format('variants.%s.imageUrls must not contain duplicates.', v_variant_index);
    end if;

    if v_variant ? 'existingId' then
      v_variant_id := (v_variant ->> 'existingId')::uuid;
      select variant.sku into v_existing_sku
        from public.product_variants variant
       where variant.id = v_variant_id
         and variant.product_id = target_product_id;
      if not found then
        raise exception using errcode = '23503', message = 'Variant does not belong to this product.';
      end if;
      v_generated_sku := v_existing_sku;
    else
      v_sequence_value := nextval('public.accessory_sku_sequence');
      if v_sequence_value > 99999999 then
        raise exception using errcode = '22003', message = 'Accessory SKU sequence is exhausted.';
      end if;
      v_generated_sku := 'ACS' || lpad(v_sequence_value::text, 8, '0');
    end if;

    v_variants := v_variants || jsonb_build_array(
      v_variant || jsonb_build_object('sku', v_generated_sku)
    );
    v_variant_index := v_variant_index + 1;
  end loop;

  v_payload := target_payload || jsonb_build_object('variants', v_variants);
  v_source_variants := v_variants;
  select item.value into v_representative
    from jsonb_array_elements(v_source_variants) item(value)
   where coalesce((item.value ->> 'isActive')::boolean, false)
   limit 1;
  if v_representative is null then
    select item.value into v_representative
      from jsonb_array_elements(v_source_variants) item(value)
     limit 1;
  end if;
  v_payload := v_payload || jsonb_build_object(
    'productImageUrls', coalesce(v_representative -> 'imageUrls', '[]'::jsonb)
  );

  return public.save_admin_accessory_product_v2(
    target_product_id,
    expected_updated_at,
    v_payload
  );
end
$function$;

revoke all on function public.save_admin_accessory_product_v3(uuid, timestamptz, jsonb)
  from public, anon, authenticated;
grant execute on function public.save_admin_accessory_product_v3(uuid, timestamptz, jsonb)
  to service_role;

comment on function public.save_admin_accessory_product_v3(uuid, timestamptz, jsonb) is
  'SKU-only accessory writer: preserves existing SKU values and allocates ACS sequence values for new variants.';

commit;
