'use client'
import { useMemo, useState } from 'react'
import Link from 'next/link'
import { Calculator, ChevronRight, Info } from 'lucide-react'
import { Header } from '@/components/header'
import { Footer } from '@/components/footer'
import type { EstimatePolicy, EstimateVehicle } from '@/lib/services/cost-estimator-service'

type Location = 'HN_HCM' | 'OTHER'
type Line = { label: string; amount: number; detail?: string; applicable?: boolean }
const currency = (value: number) => new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND', maximumFractionDigits: 0 }).format(value)
export function CostEstimator({ vehicles, policies, loadError = false }: { vehicles: EstimateVehicle[]; policies: EstimatePolicy[]; loadError?: boolean }) {
    const [vehicleId, setVehicleId] = useState(vehicles[0]?.id ?? ''), [location, setLocation] = useState<Location>('HN_HCM'), [loanPercent, setLoanPercent] = useState(80), [loanDuration, setLoanDuration] = useState(60), [interestRate, setInterestRate] = useState(8.5)
    const vehicle = vehicles.find((item) => item.id === vehicleId) ?? vehicles[0]
    const calculation = useMemo(() => { if (!vehicle) return null; const isCar = vehicle.category === 'CAR'; const vehicleType = isCar ? 'ELECTRIC_CAR' : 'ELECTRIC_MOTORBIKE'; const policy = (feeType: EstimatePolicy['feeType']) => policies.filter((item) => item.feeType === feeType && item.vehicleType === vehicleType && (item.provinceCode === null || item.provinceCode === location)).sort((a, b) => Number(b.provinceCode === location) - Number(a.provinceCode === location))[0]; const reg = policy('REGISTRATION_FEE'); const plate = policy('PLATE_FEE'); const road = isCar ? policy('ROAD_FEE') : undefined; const insurance = policy('CTP_INSURANCE'); const amount = (item: EstimatePolicy | undefined) => !item ? 0 : item.calculationType === 'PERCENT' ? vehicle.price * item.value / 100 : item.value; const lines: Line[] = [{ label: 'Lệ phí trước bạ', amount: amount(reg), detail: reg?.calculationType === 'PERCENT' ? `${reg.value}% giá xe` : reg?.name }, { label: 'Phí đăng ký biển số', amount: amount(plate), detail: plate?.name }, { label: 'Phí sử dụng đường bộ', amount: amount(road), detail: isCar ? road?.name : 'Không áp dụng cho xe máy điện', applicable: isCar }, { label: 'Bảo hiểm TNDS', amount: amount(insurance), detail: insurance?.name }]; const feeTotal = lines.reduce((sum, line) => sum + line.amount, 0), onRoadTotal = vehicle.price + feeTotal, loanAmount = vehicle.price * loanPercent / 100, initialPayment = onRoadTotal - loanAmount, firstMonth = loanAmount / loanDuration + loanAmount * (interestRate / 100) / 12; return { lines, feeTotal, onRoadTotal, loanAmount, initialPayment, firstMonth } }, [vehicle, location, policies, loanPercent, loanDuration, interestRate])
    const cars = vehicles.filter((item) => item.category === 'CAR'), bikes = vehicles.filter((item) => item.category === 'MOTORBIKE')
    return <main className="flex min-h-screen flex-col bg-background pt-[74px]"><Header /><div className="border-b border-black/5 bg-muted py-16"><div className="mx-auto max-w-[1440px] px-6 text-center lg:px-12"><div className="mb-6 flex items-center justify-center gap-2 text-xs font-semibold uppercase tracking-widest text-muted-foreground"><Link href="/">Trang chủ</Link><ChevronRight size={14} /><span>Dự toán chi phí</span></div><h1 className="text-4xl font-bold sm:text-6xl">Dự toán chi phí</h1><p className="mx-auto mt-4 max-w-2xl text-muted-foreground">Chọn ô tô hoặc xe máy điện để xem chi tiết giá xe và các khoản chi phí dự toán phù hợp.</p></div></div>
        <div className="mx-auto w-full max-w-[1200px] px-6 py-14 lg:px-12">{loadError ? <div className="rounded-xl border border-red-200 bg-red-50 p-6 text-center text-red-700">Không thể tải dữ liệu dự toán.</div> : !vehicle || !calculation ? <div className="rounded-xl border p-8 text-center text-muted-foreground">Chưa có xe đang hoạt động và có giá bán để dự toán.</div> : <div className="grid gap-10 lg:grid-cols-5"><div className="space-y-9 lg:col-span-3"><section><h2 className="mb-5 flex items-center gap-2 text-2xl font-bold"><Calculator className="text-brand-600" />Chọn xe và địa phương</h2><div className="grid gap-5 md:grid-cols-2"><label className="text-sm font-semibold">Dòng xe<select value={vehicle.id} onChange={(e) => setVehicleId(e.target.value)} className="mt-2 h-12 w-full rounded-xl border bg-white px-4"><optgroup label={`Ô tô điện (${cars.length})`}>{cars.map((item) => <option key={item.id} value={item.id}>{item.name} — {currency(item.price)}</option>)}</optgroup><optgroup label={`Xe máy điện (${bikes.length})`}>{bikes.map((item) => <option key={item.id} value={item.id}>{item.name} — {currency(item.price)}</option>)}</optgroup></select></label><label className="text-sm font-semibold">Nơi đăng ký<select value={location} onChange={(e) => setLocation(e.target.value as Location)} className="mt-2 h-12 w-full rounded-xl border bg-white px-4"><option value="HN_HCM">Hà Nội / TP.HCM</option><option value="OTHER">Tỉnh / thành khác</option></select></label></div><div className="mt-5 rounded-xl bg-brand-50 p-4"><p className="text-xs font-semibold uppercase text-brand-700">{vehicle.category === 'CAR' ? 'Ô tô điện' : 'Xe máy điện'}</p><div className="mt-1 flex items-end justify-between gap-4"><p className="text-xl font-bold">{vehicle.name}</p><p className="text-xl font-bold text-brand-600">{currency(vehicle.price)}</p></div></div></section>
            <section className="border-t pt-8"><h2 className="mb-5 text-2xl font-bold">Chi tiết các khoản dự toán</h2><div className="overflow-hidden rounded-xl border bg-white">{calculation.lines.map((line) => <div key={line.label} className="flex items-start justify-between gap-5 border-b px-5 py-4 last:border-0"><div><p className="font-semibold">{line.label}</p>{line.detail && <p className="mt-1 text-xs text-muted-foreground">{line.detail}</p>}</div><span className={`shrink-0 font-bold ${line.applicable === false ? 'text-muted-foreground' : 'text-brand-600'}`}>{line.applicable === false ? 'Không áp dụng' : currency(line.amount)}</span></div>)}</div></section>
            <section className="border-t pt-8"><h2 className="mb-5 text-2xl font-bold">Phương án trả góp tham khảo</h2><div className="space-y-6"><label className="block text-sm font-semibold">Tỷ lệ vay: <span className="text-brand-600">{loanPercent}%</span><input type="range" min="0" max="80" step="5" value={loanPercent} onChange={(e) => setLoanPercent(Number(e.target.value))} className="mt-3 w-full accent-slate-900" /></label><label className="block text-sm font-semibold">Thời gian vay: <span className="text-brand-600">{loanDuration} tháng</span><input type="range" min="12" max="96" step="12" value={loanDuration} onChange={(e) => setLoanDuration(Number(e.target.value))} className="mt-3 w-full accent-slate-900" /></label><label className="block text-sm font-semibold">Lãi suất dự kiến: <span className="text-brand-600">{interestRate}%/năm</span><input type="range" min="5" max="15" step="0.1" value={interestRate} onChange={(e) => setInterestRate(Number(e.target.value))} className="mt-3 w-full accent-slate-900" /></label></div></section></div>
            <aside className="lg:col-span-2"><div className="sticky top-[100px] rounded-3xl bg-foreground p-8 text-background shadow-2xl"><h2 className="mb-7 text-xl font-bold">Tổng hợp dự toán</h2><div className="space-y-4 text-sm"><div className="flex justify-between gap-4"><span className="text-white/60">Giá xe</span><b>{currency(vehicle.price)}</b></div><div className="flex justify-between gap-4"><span className="text-white/60">Tổng phí</span><b>{currency(calculation.feeTotal)}</b></div><div className="flex justify-between gap-4 border-t border-white/10 pt-5 text-lg"><b>Tổng lăn bánh</b><b className="text-brand-400">{currency(calculation.onRoadTotal)}</b></div></div><div className="mt-7 space-y-4 border-t border-white/10 pt-7 text-sm"><div className="flex justify-between"><span className="text-white/60">Số tiền vay</span><b>{currency(calculation.loanAmount)}</b></div><div className="flex justify-between"><span className="text-white/60">Trả trước</span><b>{currency(calculation.initialPayment)}</b></div><div className="rounded-xl bg-white/5 p-4"><p className="text-white/60">Thanh toán tháng đầu dự kiến</p><p className="mt-1 text-2xl font-bold text-brand-400">{currency(calculation.firstMonth)}</p></div></div><p className="mt-6 flex gap-2 text-xs text-white/50"><Info size={14} className="shrink-0" />Kết quả chỉ mang tính tham khảo và được tính từ các chính sách dự toán đang hoạt động.</p></div></aside></div>}</div><Footer /></main>
}